[#Library-displayName]
= xref:Library.adoc[Library]::displayName
:relfileprefix: ../
:mrdocs:


Get the display name for the library in the current runtime context&period;

== Synopsis

Declared in `&lt;https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/minecraft/Library.h#L125[minecraft&sol;Library&period;h]&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:QString.adoc[QString]
displayName(xref:RuntimeContext.adoc[RuntimeContext] const& runtimeContext) const;
----

== Description

Get the file name of the library

Get the file name of the library

This function returns the display name for the library, defaulting to the filename
if no display name is set&period;

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library

Get the file name of the library



== Return Value

QString The display name of the library&period;



== Parameters

|===
| Name | Description

| *runtimeContext*
| The current runtime context&period;


|===



[.small]#Created with https://www.mrdocs.com[MrDocs]#
