[#std-__new_allocator]
= xref:std.adoc[std]::&lowbar;&lowbar;new&lowbar;allocator
:relfileprefix: ../
:mrdocs:


An allocator that uses global &grave;new&grave;, as per C&plus;&plus;03 &lsqb;20&period;4&period;1&rsqb;&period;

== Synopsis

Declared in `&lt;https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher//nix/store/2agih0y5ns3sgbviw2xhivdgg59b41g9-gcc-14-20241116/include/c++/14-20241116/bits/new_allocator.h#L62[&sol;nix&sol;store&sol;2agih0y5ns3sgbviw2xhivdgg59b41g9&hyphen;gcc&hyphen;14&hyphen;20241116&sol;include&sol;c&plus;&plus;&sol;14&hyphen;20241116&sol;bits&sol;new&lowbar;allocator&period;h]&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename &lowbar;Tp&gt;
class &lowbar;&lowbar;new&lowbar;allocator;
----




== Description

This is precisely the allocator defined in the C&plus;&plus; Standard&period;
&hyphen; all allocation calls &grave;operator new&grave;
&hyphen; all deallocation calls &grave;operator delete&grave;

This is the default base&hyphen;class implementation of &grave;std&colon;&colon;allocator&grave;,
and is also the base&hyphen;class of the &grave;&lowbar;&lowbar;gnu&lowbar;cxx&colon;&colon;new&lowbar;allocator&grave; extension&period;
You should use either &grave;std&colon;&colon;allocator&grave; or &grave;&lowbar;&lowbar;gnu&lowbar;cxx&colon;&colon;new&lowbar;allocator&grave;
instead of using this directly&period;



== Template Parameters

|===
| Name | Description

| *&lowbar;Tp*
| Type of allocated object&period;


|===



[.small]#Created with https://www.mrdocs.com[MrDocs]#
