[#std-allocator]
= xref:std.adoc[std]::allocator
:relfileprefix: ../
:mrdocs:


The
_standard_
allocator, as per C&plus;&plus;03 &lsqb;20&period;4&period;1&rsqb;&period;

== Synopsis

Declared in `&lt;https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher//nix/store/2agih0y5ns3sgbviw2xhivdgg59b41g9-gcc-14-20241116/include/c++/14-20241116/bits/allocator.h#L127[&sol;nix&sol;store&sol;2agih0y5ns3sgbviw2xhivdgg59b41g9&hyphen;gcc&hyphen;14&hyphen;20241116&sol;include&sol;c&plus;&plus;&sol;14&hyphen;20241116&sol;bits&sol;allocator&period;h]&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename &lowbar;Tp&gt;
class allocator
    : public xref:std/__allocator_base.adoc[&lowbar;&lowbar;allocator&lowbar;base]&lt;&lowbar;Tp&gt;;
----




== Description

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

Classes encapsulating memory operations&period;

@&lcub;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

Classes encapsulating memory operations&period;

@&lcub;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

Classes encapsulating memory operations&period;

@&lcub;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;

See https&colon;&sol;&sol;gcc&period;gnu&period;org&sol;onlinedocs&sol;libstdc&plus;&plus;&sol;manual&sol;memory&period;html&num;std&period;util&period;memory&period;allocator
for further details&period;



== Template Parameters

|===
| Name | Description

| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


| *&lowbar;Tp*
| Type of allocated object&period;


|===



[.small]#Created with https://www.mrdocs.com[MrDocs]#
