[#Net-ApiDownload-makeFile]
= xref:Net.adoc[Net]::xref:Net/ApiDownload.adoc[ApiDownload]::makeFile
:relfileprefix: ../../
:mrdocs:


== Synopsis

Declared in `&lt;https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/net/ApiDownload.h#L29[net&sol;ApiDownload&period;h]&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:Net/Download.adoc[Download]::xref:Net/Download/Ptr.adoc[Ptr]
makeFile(
    xref:QUrl.adoc[QUrl] url,
    xref:QString.adoc[QString] path,
    xref:Net/Download.adoc[Download]::xref:Net/NetRequest/Options.adoc[Options] options = Download&colon;&colon;Option&colon;&colon;NoOptions);
----



[.small]#Created with https://www.mrdocs.com[MrDocs]#
