[#Net-Download-makeFile]
= xref:Net.adoc[Net]::xref:Net/Download.adoc[Download]::makeFile
:relfileprefix: ../../
:mrdocs:


== Synopsis

Declared in `&lt;https://github.com/PrismLauncher/PrismLauncher/blob/develop/net/Download.h#L58[net&sol;Download&period;h]&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
static
xref:Net/Download.adoc[Download]::xref:Net/Download/Ptr.adoc[Ptr]
makeFile(
    xref:QUrl.adoc[QUrl] url,
    xref:QString.adoc[QString] path,
    xref:Net/NetRequest/Options.adoc[Options] options = Option&colon;&colon;NoOptions);
----



[.small]#Created with https://www.mrdocs.com[MrDocs]#
